; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2_custom
build_flags=
	-std=c++20
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 15m
lib_deps = 
	electroniccats/MPU6050@^1.4.4
	adafruit/Adafruit BMP280 Library@^2.6.8
	adafruit/Adafruit MPU6050@^2.2.6

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17

